##################################################################################################
# Product Page service
################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: productpage
  labels:
    app: productpage
    service: productpage
spec:
  type: LoadBalancer
  ports:
  - port: 9080
  selector:
    app: productpage

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: productpage-v1
  labels:
    app: productpage
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productpage
      version: v1
  template:
    metadata:
      labels:
        app: productpage
        version: v1
    spec:
      containers:
      - name: productpage
        image: carlavila2205103/practica_creativa2p3-productpage:latest  # Replace with your custom image reference
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9080
        env:
        - name: GROUPO_NUMERO
          value: "30"